name: Speedtest
on:
  workflow_dispatch:
  schedule:
    - cron: "* */2 * * *"

jobs:
  speedtest:
    container:
      image: python:3.8-buster
    runs-on: ubuntu-latest
    env:
      history_file: 'history/internet-speed-test.csv'
    steps:
      - uses: actions/checkout@v2
      
      - name: Get Time From Internet
        id: time
        uses: Plabick/Remote-Time-Action@V1.0
        with:
          timezone: EST
      
      - name: Install Dependencies 
        run: pip3 install quickchart.io speedtest-cli

      - name: Conduct Speedtest
        id: speedtest
        run: python3 ./resources/conduct-speedtest.py ${{env.history_file}} ${{steps.time.outputs.unixTime}}
     
      - name: Generate Graphs
        id: graphs
        run: python3 ./resources/generate-graphs.py ${{env.history_file}} ${{steps.time.outputs.unixTime}}
      
      - name: Update Readme
        id: readme
        run: |
          cat << EOF > README.md
          # Github Action Runner Network Performance 
          A record of Github's Action Runners network speed over time. Updated every 2 hours
          ### Latest Metrics
          ${{ steps.speedtest.outputs.upload }} ${{ steps.speedtest.outputs.download }} ${{ steps.speedtest.outputs.ping }}
          ### Historical Data
          #### Last 24 Hours 
           ${{ steps.graphs.outputs.uploadChart12 }}
           ${{ steps.graphs.outputs.downloadChart12 }}
           ${{ steps.graphs.outputs.pingChart12 }}
          #### Last Week
           ${{ steps.graphs.outputs.uploadChart84 }}
           ${{ steps.graphs.outputs.downloadChart84 }}
           ${{ steps.graphs.outputs.pingChart84 }}
          #### Last Month
           ${{ steps.graphs.outputs.uploadChart336 }}
           ${{ steps.graphs.outputs.downloadChart336 }}
           ${{ steps.graphs.outputs.pingChart336 }}
          EOF
        shell: bash
      
      - name: Publish Changes
        run: |
             git config --local user.email ${{secrets.EMAIL}}
             git config --local user.name  ${{secrets.USERNAME}}
             git add ${{env.history_file}} README.md
             git commit -m "Update Speed Test History" 
             git push origin main || git pull --allow-unrelated-histories && git push origin main      
